"""initial schema

Revision ID: 949b4c5d2142
Revises: 
Create Date: 2026-08-09 15:54:48.131827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949b4c5d2142'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soil_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('organic_carbon', sa.Float(), nullable=False),
    sa.Column('moisture', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('soil_health_score', sa.Float(), nullable=False),
    sa.Column('soil_quality', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('nutrient_status', sa.JSON(), nullable=True),
    sa.Column('deficiencies', sa.JSON(), nullable=True),
    sa.Column('crop_recommendations', sa.JSON(), nullable=True),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soil_analyses')
    op.drop_table('model_runs')
    op.drop_table('fields')
    op.drop_table('datasets')
    # ### end Alembic commands ###
