"""
Soil-health forecast endpoint.

If a field has real historical analyses stored in the database, those are
used as the "history" series. Because most demo installs won't have weeks
of real sensor history, the forward-looking "forecast" series is always
generated via a simple trend-projection model and is explicitly labeled
`is_forecast: true` / `is_synthetic` in the response so the frontend can
visually distinguish it from real measurements.
"""
from datetime import datetime, timedelta, timezone
from typing import Optional

import numpy as np
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.db.database import get_db
from app.db import models as db_models
from app.schemas.schemas import ForecastResponse, ForecastPoint

router = APIRouter()

DISCLAIMER = (
    "The 'forecast' series is generated by a simple trend-projection model over "
    "available history (or clearly-labeled synthetic demo data when no history "
    "exists) for demonstration purposes, and is not a substitute for agronomic advice."
)


def _synthetic_history(days: int = 30):
    rng = np.random.default_rng(7)
    base_score = 62.0
    points = []
    today = datetime.now(timezone.utc)
    score = base_score
    n, p, k, moisture = 80.0, 40.0, 60.0, 45.0
    for i in range(days, 0, -1):
        date = today - timedelta(days=i)
        score = float(np.clip(score + rng.normal(0, 1.5), 20, 95))
        n = float(np.clip(n + rng.normal(0, 2), 20, 180))
        p = float(np.clip(p + rng.normal(0, 1.5), 10, 100))
        k = float(np.clip(k + rng.normal(0, 2), 20, 150))
        moisture = float(np.clip(moisture + rng.normal(0, 2), 10, 90))
        points.append(ForecastPoint(
            date=date.strftime("%Y-%m-%d"), soil_health_score=round(score, 1),
            nitrogen=round(n, 1), phosphorus=round(p, 1), potassium=round(k, 1),
            moisture=round(moisture, 1), is_forecast=False,
        ))
    return points, score, n, p, k, moisture


def _project_forecast(last_score, last_n, last_p, last_k, last_moisture, days: int = 14):
    rng = np.random.default_rng(11)
    points = []
    today = datetime.now(timezone.utc)
    score, n, p, k, moisture = last_score, last_n, last_p, last_k, last_moisture
    for i in range(1, days + 1):
        date = today + timedelta(days=i)
        score = float(np.clip(score + rng.normal(0.1, 1.2), 15, 98))
        n = float(np.clip(n + rng.normal(-0.3, 1.8), 15, 190))
        p = float(np.clip(p + rng.normal(-0.1, 1.2), 8, 105))
        k = float(np.clip(k + rng.normal(-0.2, 1.6), 15, 155))
        moisture = float(np.clip(moisture + rng.normal(0, 2.5), 8, 92))
        points.append(ForecastPoint(
            date=date.strftime("%Y-%m-%d"), soil_health_score=round(score, 1),
            nitrogen=round(n, 1), phosphorus=round(p, 1), potassium=round(k, 1),
            moisture=round(moisture, 1), is_forecast=True,
        ))
    return points


@router.get("/forecast/{field_id}", response_model=ForecastResponse)
def get_forecast(field_id: Optional[str], db: Session = Depends(get_db)):
    real_history = []
    if field_id and field_id != "demo":
        rows = (
            db.query(db_models.SoilAnalysis)
            .filter(db_models.SoilAnalysis.field_id == field_id)
            .order_by(db_models.SoilAnalysis.created_at.asc())
            .all()
        )
        for r in rows:
            real_history.append(ForecastPoint(
                date=r.created_at.strftime("%Y-%m-%d"),
                soil_health_score=r.soil_health_score,
                nitrogen=r.nitrogen, phosphorus=r.phosphorus, potassium=r.potassium,
                moisture=r.moisture, is_forecast=False,
            ))

    is_synthetic = len(real_history) < 5
    if is_synthetic:
        history, last_score, last_n, last_p, last_k, last_moisture = _synthetic_history()
    else:
        history = real_history
        last = history[-1]
        last_score, last_n, last_p, last_k, last_moisture = (
            last.soil_health_score, last.nitrogen, last.phosphorus, last.potassium, last.moisture
        )

    forecast = _project_forecast(last_score, last_n, last_p, last_k, last_moisture)

    return ForecastResponse(
        field_id=field_id,
        is_synthetic=is_synthetic,
        disclaimer=DISCLAIMER,
        history=history,
        forecast=forecast,
    )
